### PR TITLE
Progress Tracker Widget

### PR DESCRIPTION
**Pull request by yaatehr**
There's one issue with the merge and that is that is seems we've changed jqeury versions, so the method we use to define the widget doesn't work. That could just be because we aren't using the jquery ui anymore. Take a look.

screen shot 2018-02-01 at 5 22 02 pm

best,
Yaateh

### CODE REVIEW

**Comment by cesandoval** [comment]
Hmmm, I think at some point I was cleaning up some un-used dependencies, and jquery-ui was one of them. Have you tried merging on your local machine with master? I think using your setup should be ok!

**Review by cesandoval — COMMENTED** [review]
Hmmm, I think at some point I was cleaning up some un-used dependencies, and jquery-ui was one of them. Have you tried merging on your local machine with master? I think using your setup should be ok! 

I don't see why that would break anything. Does it work on your machine?

**Comment by yaatehr** [comment]
Yea it all works on my machine with the old jquery sourcelinks we used. I pushed up a working version with the new one commented out. It should work fine and the travis tests passed so i think its a go.

**Comment by cesandoval** [comment]
Perfect! I'll double check your branch in a bit, and merge the pull request!

**Comment by cesandoval** [comment]
Hey, so I am getting a number of errors:

- First, the progress tracker never initializes. It stays as a black box that never drops down:
screen shot 2018-02-01 at 10 11 01 pm

- Then, the widget never queries the endpoint it seems. I think the problem might be that the file is getting uploaded too quickly?
screen shot 2018-02-01 at 10 12 47 pm

I'll go without the widget for the class, but hopefully we can get it to work soon?

Let me know your thoughts.

**Comment by cesandoval** [comment]
Works pretty well in general!

There are a couple of bugs that I found:

1. When the upload is done, and is waiting to reload, the flash appears, and but the drop down menu does not show up:
screen shot 2018-02-02 at 12 32 32 pm

2. Some files never update their status to finished, despite them being done, or showing up as completed:
screen shot 2018-02-02 at 12 30 57 pm

_This is the file that I uploaded that still does not show up as completed_
[ny_resid.zip](https://github.com/cesandoval/PaintingWithData_Riyadh/files/1690249/ny_resid.zip)
**you can use the raster property LOT**

**Pull request merged**
