### PR TITLE
Share function: Project embed link and Snapshots share and create/delete

### PR DESCRIPTION
**Pull request by ooookai**
image

image

### CODE REVIEW

**Comment by cesandoval** [comment]
image
Can we extend the length of the snapshots, so it goes all the way until the end of the page? Right now, the scrollbar appear mid-way in taller screens. Perhaps it doesn't need to be a fixed length.

**Comment by cesandoval** [comment]
image
For some reason, the year shows up in the upper right corner of some of the snapshots

**Comment by cesandoval** [comment]
image
Do you think the **+** sign should always be the first element on the screenshots, so users can add new ones without having to scroll to the end? This might also mean that we sort the snapshots from newer to older.

**Comment by cesandoval** [comment]
image
The icons for copying the link and deleting the snapshot are misplaced once you have many snapshots and have to use the scrollbar to get to the latest ones.

**Comment by cesandoval** [comment]
image
When adding new snapshots, the name should not be pre-filed, but rather, have a suggested name un the background that is not typed.

**Comment by cesandoval** [comment]
When clicking on the existing snapshots, it'd be great to have the snapshot open up in a modal, so the user can look at it more closely.

**Comment by ooookai** [comment]
> image
> For some reason, the year shows up in the upper right corner of some of the snapshots

Which project id you are testing?

**Comment by cesandoval** [comment]
> > image
> > For some reason, the year shows up in the upper right corner of some of the snapshots
> 
> Which project id you are testing?

http://localhost:3000/app/91

**Comment by ooookai** [comment]
I don't think we need the word 'Model' with snapshot, it makes me confused.

**Comment by cesandoval** [comment]
Should we change it for map instead?

**Comment by ooookai** [comment]
I think it is not necessary to add any word to be in front of the 'snapshot' on the UI since user definitely know they are doing something in a 'Map'.
We may need the word 'map' or 'model' when we want to explain it in an article, but not for UI.


### Examples
- https://support.airtable.com/hc/en-us/articles/202584799-Taking-and-restoring-base-snapshots
- https://www.vmware.com/support/ws5/doc/ws_preserve_sshot_taking.html


---
image

---
image

**Comment by cesandoval** [comment]
Ok cool, sounds good!

**Comment by ooookai** [comment]
**Check the doc of HTML <a> tag below.**
To sum up, We have to store the base64 data url in the database if we want to implement the quick download function.

>This attribute only works for same-origin URLs.
> Although HTTP(s) URLs need to be in the same-origin, blob: URLs and data: URLs are allowed so that content generated by JavaScript, such as pictures created in an image-editor Web app, can be downloaded.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
image

**Comment by cesandoval** [comment]
Ok cool, i can look for an alternative. Do you wanna get started with the other server in the meantime?

**Pull request merged**
