### PR TITLE
added update geometry action

### PR DESCRIPTION
**Pull request by cesandoval**
I am not sure if this is the action function that you needed. It updates the three js geometry values, but not the JSON layers. Let me know if this works, if not I can figure something else out

### CODE REVIEW

**Comment by ooookai** [comment]
what is JSON layers? where are them?

**Comment by cesandoval** [comment]
state.layers are the JSON layers

**Comment by ooookai** [comment]
So the JSON layers didn't contain the color, opacity, right ?

**Comment by cesandoval** [comment]
yes, and other data

**Comment by ooookai** [comment]
Sorry, I had edited my question comment when you responded, so I am not sure whether the JSON layer contains the color, opacity state.

**Comment by cesandoval** [comment]
the JSON layer contains the color, but not the opacity. we can add it pretty easily. but perhaps it makes more sense to have a different data structure similar to what you have on mocklayers.js?

**Comment by ooookai** [comment]
do you mean `mockData.js` ?
yes, i think so. the data structure might be similar.

**Comment by cesandoval** [comment]
yeah, `mockData.js`, but in the meantime, I will add and opacity property to the JSON layers. Then we can refractor it so it is similar to the `mockData.js`. Does that help?

**Comment by ooookai** [comment]
yes, that help a lot.
do we need both `updateGeometry` and `updateLayer` in the same time ?

**Comment by cesandoval** [comment]
ok, I will add opacity to `state.layers`. I think I can migrate everything to `Action.updateGeometry`, but perhaps we need to point the `sidebar` functions to look for that state instead of the `sidebar` state.

**Pull request merged**
