### PR TITLE
Basic Blog Support

### PR DESCRIPTION
**Pull request by panthersuper**
# - add basic blog support with html exported from google doc.

# - fix links in resource and blog page

# how to add a post

1. 
Generate blog html according to the template: [https://docs.google.com/document/d/141xi5hUUdm3t4vnsRW_NkUir_s1SMpZzi6Le-PYxgwo/edit?usp=sharing](url)

* note that the basic structure should be kept, just change the contents. keep "Overview"
* It support videos. Follow the example in the template and just change video by changing the video url; Keep the width, height settings.

2.
unzip the generated files, should have a html file and a image folder. copy/mv the files under the /public/posts directory with a new entry.

3.
In `blog.jade`, add a new iframe section with the url to the new post, it should have a unique id.
like:
```
  div.section_content.row
    div.container.ifwrapper
      iframe(src="posts/test/index.html", id="post1", style="" class = "iframe_post")
```
add a new piece of code to reframe the newly added iframe, like:
```
    $("#post1").load(function () {
      fixiframe("#post1");
      expand_function("post1",);
    });
```

### CODE REVIEW

**Review by cesandoval — CHANGES_REQUESTED** [review]
Looks great! The only thing is that when clicking on the PWD Icon, we should just redirect to home, instead of `home/#`. Also, when on the documentation page and the blog page, it you click on the PWD icon, it does not redirect to home, it just appends the `#` to the route.

Can we get rid of the grey square around the blog post?

**Comment by panthersuper** [comment]
@cesandoval the # link when clicking the icon will help to return to the top (when in home page).

I just fixed the ones you mentioned for doc/blog pages.

meanwhile, we can keep this PR for the moment for you to update the blog contents.

**Comment by cesandoval** [comment]
Awesome! Will look into it and merge once we add the blog post

**Comment by panthersuper** [comment]
@cesandoval Added post 1 to blog. Also updated home page's bg img and some fonts. Feel free to change!

**Review by cesandoval — APPROVED** [review]

**Pull request merged**
