### PR TITLE
Several Updates and Redux refactoring

### PR DESCRIPTION
**Pull request by ooookai**
# Redux Refactoring Plan

## Reducer Datasets Replace Sidebar

Ref to issue #162 [Redux States.sidebar check]
- [X] **1**: use `!_.isEmpty(newProps.layers)`
- [X] **2**: use `!_.isEmpty(nprops.layers)`
- [X] **3**: use `Object.entries(layers)`
- [X] **4**: remove `this.layers`
- [X] **5**: use `this.newProps.datasets.minMax`
- [X] **6**: use `this.newProps.datasets.allIndices`
- [X] **7**: use `Object.values(layers)` and `!_.isEmpty(layers)`
- [X] **8**: use `_.first(this.props.layers)`

> use `!_.isEmpty(layers)` to checks if object is an empty.
> replace all `sidebar.layers` to `datasets.layers`, or remove it if it's useless.
> fix: use `Object.values(this.props.layers)[0]` replace `_.first(this.props.layers)`

-----------------------------------------------------------------

## Interaction

apply interaction states: `loading`, `panelShow`, `activeNode`.

- [X] panelShow: `jsx/options.js`, `jsx/map.js`
- [X] activeNode: `jsx/rVpl.js`
- [X] fix panelShow action with {value: 'panelName'}
-

-----------------------------------------------------------------

## Options

check options operaction and behavior is working

- [X] knnValue: `knnSlider.js`
- [X] opacity: `opacitySlider.js`
- [X] bgStyle: `optionsMapStyle.js` 

-----------------------------------------------------------------

- [X] draft reducer `vpl` and `map`
- [X] update actions in `rVpl.js`
- [X] add `nodeOutput` to output voxel geometry to map
- [X] update actions in `vprog/Panel.js`, `vprog/Slider.js` and `sidebar/layer.js` [ ] merged
- [X] rename `rVpl.js ` function `linkThenComputeNode()`, may be `computeNodes()`
- [X] fix ref problem of vpl computing 

	

!!! deprecate allNodeUpdate action

-----------------------------------------------------------------
## Influenced by Datasets and Geometries Structure changed
- [X] update `pcoord.js`
- [X] update `knnSlider.js`

-----------------------------------------------------------------
## Actions updates
- [X] nodeUpdate: `sidebar/layers.js`, `vprog/Slider.js`, `vprog/Panel.js`

-----------------------------------------------------------------
### functions work
- [X] P Coord (Query Data)
- [X] Sidebar opacity Sliders
- [X] Sidebar knn Sliders
- [X] Zoom to Map
- [X] VPL operation: 'create', 'link', 'delete', 'move'
- [X] VPL node <Panel> functionality: 'filter', 'options', 'opacity', 'color', 'delete'

### check render props
- [ ] 

### clean up 
- [ ]

-----------------------------------------------------------------
## Next Refactoring
- [ ] optimize node output geometries update logic and cache: `vprog/rVpl.js`
- [ ] rewrite 'sidebar' components
- [ ] refactor `knnSlider` functions, do not operate the geometry raw data inside the component.
- [ ] move `addVoxelGeometry()` to reducer, to solve props async problem.
- [ ] refactor `pcoords.js`

-----------------------------------------------------------------
## Do it later (not urgent)
- [ ] move `knn` operaction into reducer.
- [x] replace window.mapboxStyle to window.mapBgStyle
- [x] refacotor `hashKey`s by `time string + random string`
- [ ] use `color` to replace `color1` and `color2`
- [ ] use `import * as Act from '../store/actions'` instead `act` or `Action` as redux actions
- [ ] use arrow function `XXX = () => { }` for all jsx class functions
- [ ] rename `dataset.layerKey` to `dataset.datasetKey`
- [ ] `this.newProps = newProps` might not need it.
- [ ] use the same var name `(props)` for all `componentWillReceiveProps()` function
- [ ] clean up useless mapStateToProps: `layer.js`, 
- [ ] deprecate `color1`, `color2`, `startColor` and `endColor`.
- [ ] decouple layers property from `dataset.layers` to `vpl.nodes` for components redering.
- [ ] remove `showSidebar` of dataset layer
- [ ] move `initDatasetNode()` and `newNodeObj` to vpl reducer.
- [ ] `layer` to `datasets`: `layer.showSidebar` in `sidebar/layers.js` and `sidebar/layer.js`
- [ ] `layer` to `datasets`: `layer.visible` in `pcoord.js` and `sidebar/layer.js`

## Next Step
- [ ] store states `state.options` and save the states
- [ ] display more information of node which is hoverd(activeNode)

### loading
- [ ] add <Loading/> cover component, add virtual progress bar

-----------------------------------------------------------------
## Need Help

**Temporary fixed**
- [ ] datasets' layerKey is `null` from database

**Check function**
- [ ] SVG exporter

**urgent**
- [ ]

### CODE REVIEW

**Comment by ooookai** [comment]
# Before - After

## Avoid operating pixel geometry in component

### Before

### After


|   Before   |  After    |
| ---- | ---- |
| image | image |
 |  image    |   image  |

---

## Integrate action and reducer for one operation

|   Before   |  After    |
| ---- | ---- |
| image | image |

**Comment by cesandoval** [comment]
**Current Bugs**
- [x] Hide Map Not Working
- [x] PCoords: When only one layer is filtered, the rest of the geometries disappear until they are filtered too.
- [x] PCoords / Compute Data: When clicking on the Compute / Query Data buttons, the widgets are not being hidden/shown.
  - The error happens because when setting one of the pcoords material values, the other one is set to: `pixels.material.uniforms.min.value = NaN`
- [x] Opacity: When the general opacity slider is modified, the individual nodes' opacities are not changed.
- [ ] VPL: Geometry not being added when a new node is created. It is added until the node is modified, or clicked on.
- [ ] VPL: Logic Gates: When two layers are not filtered, the logic gates do not work.

**Comment by ooookai** [comment]
@cesandoval 
> The error happens because when setting one of the pcoords material values, the other one is set to: pixels.material.uniforms.min.value = NaN

What error?

> PCoords / Compute Data: When clicking on the Compute / Query Data buttons, the widgets are not being hidden/shown.

I fixed this one.

---


> VPL: Geometry not being added when a new node is created. It is added until the node is modified, or clicked on.

Sorry, I'm not sure what do you mean?
There is no input data when a new node is created, right?

---

> VPL: Logic Gates: When two layers are not filtered, the logic gates do not work.

Which two layers? filtered?
What function not work?

**Comment by ooookai** [comment]
-----------------------------------------------------------------
# New Feature

## Styled-Jsx ([Doc](https://github.com/zeit/styled-jsx))
Now, we can define css style inside each component, and it also support sass/scss syntax.

**Example**: 
``` jsx
<div className="class"> block </div>
<p> green </p>

<style jsx>{`
    p { color: green; } 
    .class {
        margin: 10px;
    }
`}</style>

```

## Webpack Alias ([Doc](https://webpack.js.org/configuration/resolve/#resolve-alias)) 
Now, we can use `@` to alias the path `private/jsx/` in each component instead of using relative paths  such as `./` or `../`.
**Before**
``` javascript
import * as Act from '../store/actions'
```
**After**
``` javascript
import * as Act from '@/store/actions'
```

**Comment by cesandoval** [comment]
@ooookai 
> The error happens because when setting one of the pcoords material values, the other one is set to: pixels.material.uniforms.min.value = NaN

> What error?

When filtering with the pcoords, one of the layers disappears. It appears back again once you filter it too.

---


> VPL: Geometry not being added when a new node is created. It is added until the node is modified, or clicked on.

> Sorry, I'm not sure what do you mean? There is no input data when a new node is created, right?

The geometry is not added once you add input data to the node. It is added until you click on the node to move it, or modify something.

---

> VPL: Logic Gates: When two layers are not filtered, the logic gates do not work.

> Which two layers? filtered? What function not work?

If two nodes are the input of a logic gate, unless both nodes that are the input are filtered the logic gate won't work. IE if one of the layers is 0-100, and the other is 20-50, it won't work, it will only work if one is 2-100 and the other 20-50 for example.

**Comment by cesandoval** [comment]
A few node types are not working:
- [ ] Not Node: Not computing or adding geometry
- [ ] XOr Node: Not computing or adding geometry
- [ ] Or Node: Not computing or adding geometry

The pcoords filter is not working unless the brush is dragged:
screen shot 2018-03-21 at 10 38 38 am

After being dragged:
screen shot 2018-03-21 at 10 40 43 am

Node filters are not working correctly:
- They are not remapped from 0 to 1.
- For example, here, the filter is from 0 to 0.5 and nothing is being filtered.
screen shot 2018-03-21 at 10 43 23 am

**Comment by cesandoval** [comment]
A few more errors that i just found:
- [ ] Log Node: After we modified the values from 0 to 1, it is not working properly. The values given are just too high.
- [ ] Geometry not being added when a new node is created. It is added until the node is modified, or clicked on.
- [ ] And Node: Not computing the actual And function. it is just returning all the voxels even if they are filtered. 
- [ ] Not Node: Not computing the right function. It is adding voxels where it should not.
- [ ] XOr Node: Not computing the right function. It is adding voxels where it should not.
- [ ] Or Node: Not computing or adding geometry

**Pull request merged**
