### PR TITLE
VPL Filter, K-Means Clustering, Linear Regression Line

### PR DESCRIPTION
**Pull request by kevinaer**
Filtering in VPL through nodes and p-coords now triggers update for subsequent nodes.

Added node for K-means clustering

Added graph for linear regression as well as export button for it.

Nodes change color when processing input

### CODE REVIEW

**Review by cesandoval — APPROVED** [review]
Overall, looks great! The new features are awesome! I found a few bugs or new things to implement
- When filtering the linear regression node (or really any other type of node), the changes still do not get propagated down the stream to update other nodes. For example see images below:
image
_Without filtering_
image
_After filtering_
image
_Not node not updating after filtering_

- Adding a graph (maybe a bar chart) of the distribution of cluster values for the clustering node would be great!

- For some reason, the + for adding additional nodes is not working anymore, seems like the drag functionality is getting in the way.
image

- The export graph for the regression node is great! It'd be good to name the exported file as the nodes that are being computed, and also have the axis with the names of the nodes that are inputs to the regression

- For the export, once the export as svg is implemented, it'd be great to have a dropdown menu that lets the user choose to export as a png, or svg

- The export icon could go inline on the right of the graph title: **best fit line**, so there is not so much space on top of the graph.

**Review by cesandoval — CHANGES_REQUESTED** [review]
Also, it seems like the **ml-matrix** library that is part of the  **ml-kmeans** library is breaking the bundling, which we need to be able to push to the server. This is the error:
`ERROR in bundle.js from UglifyJs
Unexpected token: name (BaseView) [./node_modules/ml-matrix/src/views/base.js:4,0][bundle.js:13324,6]
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

you can replicate it by running `yarn build`

If we cannot fix it here, we can disable eslint for this file for now

**Comment by kevinaer** [comment]
Still addressing some of the comments you mentioned but the webpack issue is fixed!

**Comment by cesandoval** [comment]
Awesome! I'll check it out and merge! Thanks so much!

**Review by cesandoval — APPROVED** [review]

**Pull request merged**
