### PR TITLE
[Testing] use `webpack build` to replace `gulp build`

### PR DESCRIPTION
**Pull request by ooookai**
I am not sure whether the new webpack config is right.
So we should run it on the server mode to check the new bundle.js file is worked correctly.

it might reduce the file size of `bundle.js`
> 15.6 Mb -> 1.06 Mb

### CODE REVIEW

**Comment by ooookai** [comment]
check the issue #130

**Comment by cesandoval** [comment]
@ooookai seems like when we run yarn run dev it works, but when we do yarn run build, it does not work. Perhaps it is because it is trying to reach the production setting instead?

**Comment by ooookai** [comment]
I don't think so, it works on my computer. 
the problem I concern is the new `bundle.js` file might not work on the server environment because I set a wrong config for the related file path.

Can you give me the error message when you run `yarn build`?

> Perhaps you can reinstall the node_modules( remove the folder and then run `yarn` to install 
everything again), I found it had some error caused by package version when I ran it, but I am not sure whether it is related.

**Comment by cesandoval** [comment]
Sorry, the problem is when I run `yarn run start`. The page just never loads, but no error message. I think this might have to do with having the server configuration instead?

**Comment by cesandoval** [comment]
This is the error i get:

`SequelizeConnectionError: connect ETIMEDOUT 54.227.111.118:5432
    at /Users/csandova/Documents/Github/PaintingWithData_Riyadh/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:110:20
    at Connection.<anonymous> (/Users/csandova/Documents/Github/PaintingWithData_Riyadh/node_modules/pg/lib/client.js:177:5)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (/Users/csandova/Documents/Github/PaintingWithData_Riyadh/node_modules/pg/lib/connection.js:63:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

**Pull request merged**
